const ActionTypes = {
  FETCH_COMPANIES: "FETCH_COMPANIES",
  SAVE_COMPANY: "SAVE_COMPANY",
  DELETE_COMPANY: "DELETE_COMPANY",
  FETCHING_API: "FETCHING_API",
  ERROR_MESSAGE: "ERROR_MESSAGE",
  CLEAR_ERROR_MESSAGE: "CLEAR_ERROR_MESSAGE"
};
export default ActionTypes;
